"""empty message

Revision ID: 004daca3390a
Revises: 57038a8530f0
Create Date: 2022-06-06 11:55:13.314389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004daca3390a'
down_revision = '57038a8530f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'student_or_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'student_or_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
