"""empty message

Revision ID: 3537f5932c65
Revises: 48538eb37bf7
Create Date: 2022-05-25 18:43:23.881592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3537f5932c65'
down_revision = '48538eb37bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('question_1', sa.String(length=200), nullable=False),
    sa.Column('question_2', sa.String(length=200), nullable=False),
    sa.Column('question_3', sa.String(length=200), nullable=False),
    sa.Column('question_4', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment')
    # ### end Alembic commands ###
