"""empty message

Revision ID: 48538eb37bf7
Revises: 13dd3914e8d9
Create Date: 2022-05-25 18:11:21.156722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48538eb37bf7'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('written_content', sa.String(length=1250), nullable=False),
    sa.Column('image', sa.String(length=50000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('content')
    # ### end Alembic commands ###
