"""empty message

Revision ID: 6002c1c151d8
Revises: 3537f5932c65
Create Date: 2022-06-06 10:14:29.433570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6002c1c151d8'
down_revision = '3537f5932c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('subjects', sa.String(length=100), nullable=False),
    sa.Column('why_you_teach', sa.String(length=200), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('fun_info', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('assessment')
    op.add_column('content', sa.Column('introduction', sa.String(length=2000), nullable=False))
    op.add_column('content', sa.Column('subject', sa.String(length=120), nullable=False))
    op.add_column('content', sa.Column('summary', sa.String(length=1250), nullable=False))
    op.alter_column('content', 'written_content',
               existing_type=sa.VARCHAR(length=1250),
               type_=sa.String(length=5000),
               existing_nullable=False)
    op.drop_column('content', 'user_id')
    op.add_column('user', sa.Column('student_or_teacher', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'student_or_teacher')
    op.add_column('content', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('content', 'written_content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1250),
               existing_nullable=False)
    op.drop_column('content', 'summary')
    op.drop_column('content', 'subject')
    op.drop_column('content', 'introduction')
    op.create_table('assessment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_1', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('question_2', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('question_3', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('question_4', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='assessment_pkey')
    )
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
