"""empty message

Revision ID: 6e84b637adc4
Revises: c61f24e7271f
Create Date: 2022-06-10 16:11:28.786075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e84b637adc4'
down_revision = 'c61f24e7271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'image',
               existing_type=sa.VARCHAR(length=50000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'image',
               existing_type=sa.VARCHAR(length=50000),
               nullable=False)
    # ### end Alembic commands ###
