"""empty message

Revision ID: 8624d15c7edb
Revises: 6e84b637adc4
Create Date: 2022-06-12 01:42:24.381587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8624d15c7edb'
down_revision = '6e84b637adc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('key_word1', sa.String(length=30), nullable=True))
    op.add_column('content', sa.Column('key_word2', sa.String(length=30), nullable=True))
    op.add_column('content', sa.Column('key_word3', sa.String(length=30), nullable=True))
    op.add_column('content', sa.Column('question1', sa.String(length=500), nullable=True))
    op.add_column('content', sa.Column('question2', sa.String(length=500), nullable=True))
    op.add_column('content', sa.Column('question3', sa.String(length=500), nullable=True))
    op.add_column('content', sa.Column('question4', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'question4')
    op.drop_column('content', 'question3')
    op.drop_column('content', 'question2')
    op.drop_column('content', 'question1')
    op.drop_column('content', 'key_word3')
    op.drop_column('content', 'key_word2')
    op.drop_column('content', 'key_word1')
    # ### end Alembic commands ###
