"""empty message

Revision ID: c61f24e7271f
Revises: 004daca3390a
Create Date: 2022-06-06 12:00:57.440292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61f24e7271f'
down_revision = '004daca3390a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'student_or_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'student_or_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
